### ISSUE TITLE
Implement extDB2 Save handling as more reliable solution to saving game progress.

### ISSUE THREAD

**Issue by MoistBaguette** [fparma/liberation#36]
This also allows to save more properties without polluting and bloating the profile.vars file.

This will also have an impact on the development workflow as more setup is required to develop and test a mission locally (MySQL instance or SQLite setup.). Thus proper documentation and guide on setting those up would be required.

After implementing the new system, the old one will be removed, unless someone else opts in to maintain the profile.vars saving implementation.

**Comment by Cuel** [comment]
could have a .dev file used to save to profilenamespace when not "building for production"

**Comment by MoistBaguette** [comment]
I'll look into it. Ideally I'd like to aim for MySQL for prod and SQLite for dev considering SQLite is simple enough to setup and I could provide prebuilt binaries. This way I could keep the code for both prod and dev identical and have one save connector to maintain.

**Comment by MoistBaguette** [comment]
If people are very opposed to this, I'll set up initial feature parity between MySQL and Profile.Vars, but I won't be maintaining both connectors.

**Comment by MoistBaguette** [comment]
Actually, this seems like the current version https://bitbucket.org/torndeco/extdb3/downloads as opposed to extDB2, unless those 2 are 2 seperate projects.
